### ISSUE TITLE
Documentation App

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#170]
I'm going to design a web app, written in webpp itself, for its documentation.

### Docs web-app features

- Documents will be hosted in another repository
  - But the web-app/api/man-pages/... are in the SDK
  - Separating the SDK into another repository?
- Runable with the SDK's `wpp` command
- Documents are written in Markdown format
- References
  - API for references
  - Search-able
  - Terminal based help
  - man pages

### Roadmap

- [ ] Finishing #158 
- [ ] Markdown View support
- [ ] Contribution system using git
  - Use git
- [ ] Web app features
  - [ ] Markdown editor
  - [ ] Markdown preview
  - [ ] Man page generator
  - [ ] Webpp Version Selector
