### ISSUE TITLE
Splitter basic funtionality

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#34]
**Constructors for string_splits**
Ctors for `string_splits` is not complete and also buggy.

Known bug:
![IMG_20211217_231347.jpg](https://user-images.githubusercontent.com/12122474/146632929-27310fa8-17e3-4211-958e-1ca3bb48c831.jpg)

# Todo:

- [x] Fix the above bug
- [ ] Add ctor for tuple of delims as input
- [x] Check if you need to store delims
- [x] Add split methods in `istring`
- [x] Check if you need to replace char* array into array of string views
- [ ] Split into a custom struct (is it even possible without reflection?)

**Comment by the-moisrex** [comment]
I wrote a [test](https://github.com/the-moisrex/webpp/commit/8aef4750931dd97639b4b8568fbcc374da85e90b) to check if the problem is the tuple type; it's not.

**Comment by the-moisrex** [comment]
Since then, I changed the data type from tuple to array and removed the test since new types is introduced and the old ones are no longer.

**Comment by the-moisrex** [comment]
- [ ] Add ctor for tuple of delims as input
- [ ] Check if you need to store delims

**Comment by the-moisrex** [comment]
# `array<string_view>` vs. `array<char const*>`

**String View**

- [ ] requires more space
- [x] easier to implement
- [x] faster access (in theory but not in practice)

**CString**

- [ ] complicated
- [x] might require less space! (Not really)


So string view version wins. I guess I have to switch to string view version.

**Comment by the-moisrex** [comment]
Okay, new question:

**Do we even need a string_splits?**
Having a named array of string views is not bad, but making sure it's all done at compile time even though it's not that hard, it doesn't actually bring any real value. Implementing a serializable type is much cleaner than this for API point of view, even if it might be harder to implement.

So, how much array of string views actually benefit us compare to vector of string views?

**Comment by the-moisrex** [comment]
Okay, we do need an array of string views.

But **do we need it to be named?**

I think it's much easier if we use indexes for it. We don't need to put compile time names for them. And runtime names just don't fit the description of an array being efficient.

Even though it's nice to put names into indexes, we better do it with the help of serialization techniques instead of this hacky thing that we're doing.

**Comment by the-moisrex** [comment]
Also the name `string_array` seems better than `string_splits` since we're using `string_vector` too.

**Comment by the-moisrex** [comment]
Now it begs the question:

**Do we even need `string_array` and `string_vector`?**

They seem to be a good shortcut but they can be customized a lot, so what's the point?

**Comment by the-moisrex** [comment]
Now another question:

**Should we use a `splitter` class or a `split` function?**

**Comment by the-moisrex** [comment]
Okay,

##  Splitter class

- [ ] It'll complicate things for the user
- [x] we could design the algorithm in a way that the computer doesn't have to calculate all the string and it can just stop at the place where the user needs. It will definitely complicate the API and it will be less efficient when used for the whole is string compared to when the function is used.

## Split function

- [x] simpler algorithm
- [x] simpler API
- [ ] less features

**Comment by the-moisrex** [comment]
Or we could just implement both!

**Comment by the-moisrex** [comment]
**template parameters**

- [ ] string names
- [x] string view type
- [ ] the number or splits
- [ ] delimiter type list

**ctors for `splitter`**

- [x] delimiters list
- [ ] string view


**So the methods for `splitter`**

- [ ] `operator++`: find the next split
- [ ] `split`: find all
- [ ] `next`: same as operator++

**Comment by the-moisrex** [comment]
![IMG_20211222_234419.jpg](https://user-images.githubusercontent.com/12122474/147207405-8c6dbb0a-9e29-4d96-ac66-3edd99d31cfb.jpg)

Okay, based on this benchmark, finding char is faster than finding strings. And delimiters are most likely to be chars, so I can't just use an array or vector of strings to simplify the `splitter` templated class signature.

**Comment by the-moisrex** [comment]
![IMG_20211223_024812.jpg](https://user-images.githubusercontent.com/12122474/147235964-d71eab10-ceaf-4930-a56a-d33874a54e98.jpg)

Okay the last comment about finding char speed is wrong. Because I used string view, the compiler optimized that fully. Dynamic strings change the result into something different.

Also check out this tweet: https://twitter.com/the_moisrex/status/1473969048585134085?t=7p6pOaYrpqKIl7IdaA5R-A&s=19

**Comment by the-moisrex** [comment]
Okay the tests are passing now! I'm scared to add new tests. 😅

**Comment by the-moisrex** [comment]
Okay new tests are now passing. Good enough.

Now, why did we wrote this utility in the first place??? 😅

**Comment by the-moisrex** [comment]
Ooops! I found bugs;

The iterator doesn't find the end part of the second delimiter for some reason

![image](https://user-images.githubusercontent.com/12122474/148430160-ec255937-6d5b-46ee-93aa-c58022c69e39.png)

**Comment by the-moisrex** [comment]
Turns out the constexpr version has another issue as well;
The size should be 3, but it splits into 2.
![image](https://user-images.githubusercontent.com/12122474/148496615-9701bf50-2094-4b11-9fbc-b2fcd589754a.png)

**Comment by the-moisrex** [comment]
> Turns out the constexpr version has another issue as well; The size should be 3, but it splits into 2. ![image](https://user-images.githubusercontent.com/12122474/148496615-9701bf50-2094-4b11-9fbc-b2fcd589754a.png)

Oh, turns out it was just my mistake that I made in the tests itself.

But we do have another problem though:

![image](https://user-images.githubusercontent.com/12122474/148497040-637ebabf-57c7-4782-82a6-e5818212e53c.png)

**Comment by the-moisrex** [comment]
Okay got it fixed (the constexpr one)

**Comment by the-moisrex** [comment]
Got it fixed. Let's close it now.
