### ISSUE TITLE
io_uring IO Service

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#392]
### `io_uring` support
io_uring seems like the best option for the Linux systems for us to support.

### Todo

- [ ] Add `scheduler` support
- [x] Allocator support
- [ ] `tick` idea (try_run/round/run_ready): run ready operations and return if they ain't any
- [x] add constraints for the callback
  - [x] io_result
- [x] complete SOO impl
- [ ] deallocate unfinished requests at destructor as well
- [ ] Run operator
  - [ ] logger argument ???
  - [ ] try-catch error handling
- [ ] Remove Last ERROR ???
- [ ] Implement functions for the tests to work:
  - [ ] read
  - [ ] write
  - [ ] close
  - [ ] remove
- [ ] How to implement General Callback?
- [x] #435 
- [ ] #436

**Comment by the-moisrex** [comment]
### The scope of separation from the async stuff?

How much of the io system should be separated from the async model? Is it a good idea to separate it fully if possible?

- [ ] Separation of the io_uring/epoll/... fully
  - [ ] Common API is required for io_uring/epoll/...
  - [ ] There are common languages between IO api and the async API (like execution context)
  - [ ] Separation of the common IO API from the async world
- [ ] Putting it all back together with the help of the common IO API
