### ISSUE TITLE
IDNA Mapping Tables are too much

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#539]
IDNA Mapping tables are too big. `45KiB + 25KiB = 70KiB` is too big, and can be compressed.

```C++

static constexpr std::uint16_t not_mapped       = 0b100U << 13U;
static constexpr std::uint16_t mapped           = 0b000U << 13U; // `ignored` is mapped too
static constexpr std::uint16_t valid            = 0b100U << 13U | 0b001U;
static constexpr std::uint16_t disallowed       = 0b100U << 13U | 0b010U;
static constexpr std::uint16_t disallowed_STD3  = 0b010U << 13U;
static constexpr std::uint16_t disallowed_STD3_valid  = valid | disallowed_STD3;
static constexpr std::uint16_t disallowed_STD3_mapped = mapped | disallowed_STD3; 

/// applies the STD3 check to the flags (valid, disallowed, mapped, ...) if it's true
consteval bool STD3ified(bool UseSTD3ASCIIRules, std::uint16_t flags) noexcept {
    return UseSTD3ASCIIRules ? flags | disallowed_STD3 : flags;
}

template <bool UseSTD3ASCIIRules = false>
static constexpr bool is_mapped(std::uint16_t const flags) noexcept {  
  return flags < STD3ified(UseSTD3ASCIIRules, not_mapped);
}

template <bool UseSTD3ASCIIRules = false>
static constexpr bool is_valid(std::uint16_t const flags) noexcept {
  return flags & STD3ified(UseSTD3ASCIIRules, valid) == valid;
}

template <bool UseSTD3ASCIIRules = false>
static constexpr bool is_disallowed(std::uint16_t const flags) noexcept {
  return flags & STD3ified(UseSTD3ASCIIRules, disallowed) == disallowed;
}

strcut alignas(std::uint32_t) idna_mapping {
  std::uint16_t validity_mask;
  std::uint16_t flag_pos;
};


```

1. We don't need length, we add a zero at the end
2. The mapped_values table should be in char8_t (UTF-8)

## Todo

- [ ] Re-implement the checking algorithm
  - [ ] Focus the fast-path on checking `valid` cases
- [ ] How to compress the tables?
- [ ] STD3 values should be embedded also
- [ ] Use `Appendable` for output instead of `istl::String` in order to let iterators work as well.
- [ ] How to get `max_len`? Should we calculate or store?
- [ ] Finding the magic Rem

**Comment by the-moisrex** [comment]
Unicode 16.0 moves the STD3 rules to the validity criteria, so we're removing them in the lookup tables as well since the `disabled_STD3_*` labels are now removed from the derived txt file.

```C++

static constexpr std::uint16_t not_mapped       = 0b100U << 13U;
static constexpr std::uint16_t mapped           = 0b000U << 13U; // `ignored` is mapped too
static constexpr std::uint16_t valid            = 0b100U << 13U | 0b001U;
static constexpr std::uint16_t disallowed       = 0b100U << 13U | 0b010U;


static constexpr bool is_mapped(std::uint16_t const flags) noexcept {  
  return flags < not_mapped;
}

static constexpr bool is_valid(std::uint16_t const flags) noexcept {
  return flags & valid == valid;
}

static constexpr bool is_disallowed(std::uint16_t const flags) noexcept {
  return flags & disallowed == disallowed;
}

strcut alignas(std::uint32_t) idna_mapping {
  std::uint16_t validity_mask;
  std::uint16_t flag_pos;
};

```

**Comment by the-moisrex** [comment]
So far we're at `43.28 KiB`, but the tests are not all passing.

**Comment by the-moisrex** [comment]
We're at `45 KiB` and we're done.
