### ISSUE TITLE
Compact Logger

### ISSUE THREAD

**Issue by the-moisrex** [the-moisrex/webpp#562]
Compact Logger format:

```
uint8_t              id
Type                 warn/info/error
String               LogMSG with {} as parameters
SpecialParamName1    type/generator/getter
File                 FileName/Path
Line                 Line Number
```

```
id LogMSG\n
id LogMSG\n
\n
TIMESTAMP id SecialParam1 Param Param\n
```

Special Parameters could be:
- Request ID
- Thread ID
- User ID
- User IP Address

## Todo

- [ ] In SDK: `wpp log file.compact.log`
- [ ] In SDK: `wpp log --today file.compact.log`
- [ ] In SDK: `wpp log --from=... --to=... file.log`
- [ ] In SDK: GUI app
- [ ] `compact_logger`: writes the logs
- [ ] `compact_log_reader`: reads the logs

## Goals

- [ ] #563
- [ ] Fast, of course
- [ ] #564
- [ ] #565
